# Generated by Django 5.2 on 2025-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bigImage',
            field=models.FileField(blank=True, max_length=99, null=True, upload_to='images/'),
        ),
    ]
