# Generated by Django 5.2 on 2025-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('animals', 'Animals'), ('nature', 'Nature'), ('training', 'Training'), ('tutorials', 'Tutorials')], default='movies', max_length=50),
        ),
    ]
