# Generated by Django 5.2 on 2025-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0002_video_bigimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bigImage',
            field=models.FileField(blank=True, max_length=99, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(blank=True, max_length=99, null=True, upload_to='movies/'),
        ),
    ]
