# Generated by Django 5.2 on 2025-05-11 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0003_video_type_video_uploaded_at_alter_video_file1080p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('animals', 'Animals'), ('nature', 'Nature'), ('training', 'Training'), ('movies', 'Movies')], default='movies', max_length=50),
        ),
    ]
