# Generated by Django 5.2 on 2025-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0004_video_uploaded_by_alter_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('animals', 'Animals'), ('nature', 'Nature'), ('training', 'Training'), ('tutorials', 'Tutorials')], default='movies', max_length=50),
        ),
    ]
