# Generated by Django 5.2 on 2025-06-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0005_alter_video_bigimage_alter_video_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='bigImage',
            new_name='big_image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='descriptionDE',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='descriptionEN',
            new_name='description_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='filePreview144p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='type',
        ),
        migrations.AddField(
            model_name='video',
            name='file_preview144p',
            field=models.FileField(blank=True, max_length=99, upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[], default='movies', max_length=50),
        ),
    ]
