services:
  web:
    build: .
    container_name: videoflix_backend
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 6
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:7
    container_name: videoflix_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s


volumes:
  postgres_db: