# Generated by Django 5.1.6 on 2025-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordforgettoken',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='userprofil',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='preferred_size',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has completed the email verification process to allow login.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.  Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='sound_volume',
            field=models.IntegerField(default=50, max_length=3),
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
        migrations.DeleteModel(
            name='PasswordForgetToken',
        ),
    ]
