# Generated by Django 5.1.6 on 2025-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='username',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
