# Generated by Django 5.1.6 on 2025-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0002_remove_passwordforgettoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
