# Generated by Django 5.1.6 on 2025-07-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0002_alter_userprofil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file1080p',
            field=models.FileField(max_length=99, upload_to='movies/'),
        ),
    ]
