# Generated by Django 5.2 on 2025-05-05 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0002_rename_preferredsize_userprofil_preferred_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file1080p',
            field=models.FileField(blank=True, max_length=99, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file120p',
            field=models.FileField(blank=True, max_length=99, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file360p',
            field=models.FileField(blank=True, max_length=99, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file720p',
            field=models.FileField(blank=True, max_length=99, upload_to='movies/'),
        ),
    ]
