# Generated by Django 5.1.6 on 2025-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0004_alter_userprofil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='sound_volume',
            field=models.IntegerField(default=50),
        ),
    ]
