# Generated by Django 5.1.6 on 2025-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0007_alter_userprofil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='username',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
