# Generated by Django 5.1.6 on 2025-07-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_db', '0009_alter_userprofil_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='username',
        ),
    ]
